<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:m="http://www.oorsprong.org/websamples.countryinfo"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://www.oorsprong.org/websamples.countryinfo"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ListOfContinentsByNameResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ListOfContinentsByNameResult">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="tContinent">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sCode" type="xs:string"/>
                                        <xs:element name="sName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>